import web3 from '../utils/initWeb3'

//get company abi
let companyAbi = 
    [
        {
            "constant":true, 
            "inputs":[],
            "name":"platformManager",
            "outputs":[{"name":"","type":"address"}],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":false,
            "inputs":[{"name":"_name","type":"string"},
                {"name":"_investMoney","type":"uint256"},
                {"name":"_targetMoney","type":"uint256"},
                {"name":"_projectDescrip","type":"string"},
                {"name":"_duration","type":"uint256"}
            ],
            "name":"createFunding",
            "outputs":[],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[],
            "name":"getAllFundings",
            "outputs":[{"name":"","type":"address[]"}],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[],
            "name":"getInvestorFunding",
            "outputs":[{"name":"","type":"address[]"}],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[],
            "name":"getCreatorFundings",
            "outputs":[{"name":"","type":"address[]"}],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"constructor"
        }
    ]
//get company address
let companyAddress = '0x897A2a4592C5FF6EA7723FCFaC46EFC1fF6610f2'
//company instance
let fundingCompanyInstance = new web3.eth.Contract(companyAbi,companyAddress)

//funding contract abi
let fundingAbi = 
[
    {
        "constant":false,
        "inputs":[{"name":"index","type":"uint256"}],
        "name":"finalizeRequest",
        "outputs":[],
        "payable":false,
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"getBalance",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"deadline",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"getRequestsCount",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[{"name":"","type":"uint256"}],
        "name":"investors",
        "outputs":[{"name":"","type":"address[]"}],
        "payable":true,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"targetBalance",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"manager",
        "outputs":[{"name":"","type":"address"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {   
        "constant":false,
        "inputs":[],
        "name":"drawBack",
        "outputs":[],
        "payable":false,
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {  
        "constant":true,
        "inputs":[],
        "name":"investBalance",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[{"name":"index","type":"uint256"}],
        "name":"getRequestDetail",
        "outputs":[
            {"name":"","type":"string"},
            {"name":"","type":"uint256"},
            {"name":"","type":"address"},
            {"name":"","type":"bool"},
            {"name":"","type":"uint256"},
            {"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[{"name":"","type":"uint256"}],
        "name":"requests",
        "outputs":[
            {"name":"purpose","type":"string"},
            {"name":"cost","type":"uint256"},
            {"name":"shopAddress","type":"address","payable":true},
            {"name":"voteCount","type":"uint256"},
            {"name":"status","type":"uint8"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[{"name":"","type":"address"}],
        "name":"investMapping",
        "outputs":[{"name":"","type":"bool"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {   
        "constant":false,
        "inputs":[
            {"name":"_purpose","type":"string"},
            {"name":"_cost","type":"uint256"},
            {"name":"_shopAddress","type":"address","payable":true}],
        "name":"createRequest",
        "outputs":[],
        "payable":false,
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"projectName",
        "outputs":[{"name":"","type":"string"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"projectDescrip",
        "outputs":[{"name":"","type":"string"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"getInvestors",
        "outputs":[{"name":"","type":"address[]","payable":true}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {   
        "constant":false,
        "inputs":[{"name":"index","type":"uint256"}],
        "name":"approveRequest",
        "outputs":[],
        "payable":false,
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "constant":false,
        "inputs":[],
        "name":"invest",
        "outputs":[],
        "payable":true,
        "stateMutability":"payable",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"getInvestorsCount",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"getRemainTime",
        "outputs":[{"name":"","type":"uint256"}],
        "payable":false,
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {"name":"_projectName","type":"string"},
            {"name":"_investBalance","type":"uint256"},
            {"name":"_targetBalance","type":"uint256"},
            {"name":"_projectDescrip","type":"string"},
            {"name":"_durationInSeconds","type":"uint256"},
            {"name":"_creator","type":"address"},
            {"name":"_investorfunding","type":"address"}],
        "payable":false,
        "stateMutability":"nonpayable",
        "type":"constructor"
    }
]
let fundingInstance = new web3.eth.Contract(fundingAbi)

let newFundingInstance = () =>{
    return new web3.eth.Contract(fundingAbi)
}

export{
    fundingCompanyInstance,
    fundingInstance,
    newFundingInstance,
}